### ISSUE TITLE
use xxh3 for SIMD support

### ISSUE THREAD

**Issue by jianshu93** [hcdenbakker/colorid#38]
Hi Team,

This current fasthash version of xxhash does not support neon devices such as M series from apple. 

I saw this xxhash3 implementation: https://github.com/cberner/xxh3

Perhaps we can replace it with this xxh3, which support AVX2 and Neon at compiling time (https://github.com/cberner/xxh3/blob/a2bfd3ae2a486ef6678e1b8305bd92c02af25d85/src/xxh3.rs#L807). I will be happy to pull request if you like.

Thanks,

Jianshu

**Comment by hcdenbakker** [comment]
Hi Jianshu,
Thanks! Yes, I realized that a while ago. I am working on a completely new version of colorid, currently called 'colorid_bv' (https://github.com/hcdenbakker/colorid_bv), which already has this bug fix implemented. It is already a lot faster, mainly because of a new bigsi implementation, but it will have many more improvements in the near future, such as binary encoding of kmers, needletail for fastx handling etc. I already have a version which is many steps ahead, but I need to find some time to implement all it on the github version.

Thanks again,
-Henk
